/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ADMIN
 */
public class ViewGiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form ViewGiaoDien
     */
    public ViewGiaoDien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        pnGD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSP = new javax.swing.JButton();
        btnBH = new javax.swing.JButton();
        btnHD = new javax.swing.JButton();
        btnKH = new javax.swing.JButton();
        btnNV = new javax.swing.JButton();
        btnKM = new javax.swing.JButton();
        btnTK = new javax.swing.JButton();
        btnDX = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Untitled design.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnGD.setBackground(new java.awt.Color(255, 255, 255));
        pnGD.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Untitled design.jpg"))); // NOI18N
        pnGD.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Mun.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 6, -1, 179));

        btnSP.setBackground(new java.awt.Color(215, 243, 255));
        btnSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSP.setText("Sản Phẩm");
        btnSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPActionPerformed(evt);
            }
        });
        jPanel1.add(btnSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 203, 179, 49));

        btnBH.setBackground(new java.awt.Color(215, 243, 255));
        btnBH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBH.setText("Bán Háng");
        btnBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBHActionPerformed(evt);
            }
        });
        jPanel1.add(btnBH, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 276, 179, 49));

        btnHD.setBackground(new java.awt.Color(215, 243, 255));
        btnHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHD.setText("Hóa Đơn");
        btnHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDActionPerformed(evt);
            }
        });
        jPanel1.add(btnHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 349, 179, 49));

        btnKH.setBackground(new java.awt.Color(215, 243, 255));
        btnKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKH.setText("Khách hàng");
        btnKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHActionPerformed(evt);
            }
        });
        jPanel1.add(btnKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 423, 179, 49));

        btnNV.setBackground(new java.awt.Color(215, 243, 255));
        btnNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNV.setText("Nhân Viên");
        btnNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVActionPerformed(evt);
            }
        });
        jPanel1.add(btnNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 498, 179, 49));

        btnKM.setBackground(new java.awt.Color(215, 243, 255));
        btnKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKM.setText("Voucher");
        btnKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKMActionPerformed(evt);
            }
        });
        jPanel1.add(btnKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 571, 179, 49));

        btnTK.setBackground(new java.awt.Color(215, 243, 255));
        btnTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTK.setText("Thống kê");
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });
        jPanel1.add(btnTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 644, 179, 49));

        btnDX.setBackground(new java.awt.Color(215, 243, 255));
        btnDX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDX.setText("Đăng Xuất");
        btnDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDXActionPerformed(evt);
            }
        });
        jPanel1.add(btnDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 739, 179, 49));

        jLabel4.setText("_______________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 711, 158, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(pnGD, javax.swing.GroupLayout.PREFERRED_SIZE, 1337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPActionPerformed
         bar(btnSP);
        showPanel(new SanPhamJPanel());
    }//GEN-LAST:event_btnSPActionPerformed

    private void btnHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDActionPerformed
        // TODO add your handling code here:
          bar(btnHD);
        showPanel(new HoaDonJPanel());
    }//GEN-LAST:event_btnHDActionPerformed

    private void btnBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBHActionPerformed
        // TODO add your handling code here:
        bar(btnBH);
        showPanel(new BanHangJPanel());
    }//GEN-LAST:event_btnBHActionPerformed

    private void btnKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKMActionPerformed
        // TODO add your handling code here:
         bar(btnKM);
        showPanel(new VoucherJPanel());
    }//GEN-LAST:event_btnKMActionPerformed

    private void btnDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDXActionPerformed
        // TODO add your handling code here:
          bar(btnDX);
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            DangNhap dangNhap = new DangNhap();
            dangNhap.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnDXActionPerformed

    private void btnNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVActionPerformed
        // TODO add your handling code here:
        bar(btnNV);
        showPanel(new NhanVienJPanel());
    }//GEN-LAST:event_btnNVActionPerformed

    private void btnKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHActionPerformed
        // TODO add your handling code here:
        bar(btnKH);
        showPanel(new KhachHangJPanel());
    }//GEN-LAST:event_btnKHActionPerformed

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
        // TODO add your handling code here:
        bar(btnTK);
        showPanel(new ThongKeJPanel());
    }//GEN-LAST:event_btnTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new FlatLightLaf());
                } catch (UnsupportedLookAndFeelException ex) {
//            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                new ViewGiaoDien().setVisible(true);
            }
        });
    }
    public void bar(JButton btn) {
        btnSP.setOpaque(false);
        btnBH.setOpaque(false);
        btnHD.setOpaque(false);
        btnKH.setOpaque(false);
        btnNV.setOpaque(false);
        btnNV.setOpaque(false);
        btnKM.setOpaque(false);
        btnTK.setOpaque(false);
        btnDX.setOpaque(false);
        btn.setOpaque(true);
       
    }
  private void showPanel(Component component) {
    // Xóa tất cả các thành phần hiện tại trong Container (JFrame hoặc JPanel)
    pnGD.removeAll();
    // Thêm panel mới
    pnGD.add(component);
    // Cập nhật lại UI
    pnGD.revalidate();
    pnGD.repaint();
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBH;
    private javax.swing.JButton btnDX;
    private javax.swing.JButton btnHD;
    private javax.swing.JButton btnKH;
    private javax.swing.JButton btnKM;
    private javax.swing.JButton btnNV;
    private javax.swing.JButton btnSP;
    private javax.swing.JButton btnTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnGD;
    // End of variables declaration//GEN-END:variables
}
